name: Mise à jour quotidienne des statistiques Tennis

on:
  schedule:
    # S'exécute chaque jour à 04:00 UTC (soit 06:00 en France en été)
    - cron: '0 4 * * *'
  workflow_dispatch: # Permet de lancer le script manuellement en cliquant sur un bouton si besoin

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Récupérer le code du dépôt
      uses: actions/checkout@v3

    - name: Configurer Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Installer les dépendances
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Exécuter le script de scraping
      run: python scraper.py

    - name: Sauvegarder et pousser le fichier JSON mis à jour
      run: |
        git config --global user.name "GitHub Action Bot"
        git config --global user.email "actions@github.com"
        git add stats_tennis_pays.json
        # Ne fait un commit que s'il y a des changements pour éviter les erreurs
        git diff --quiet && git diff --staged --quiet || (git commit -m "Mise à jour quotidienne du JSON" && git push)
